# Font
font_family Cascadia Mono

font_size 12

# Cursor
shell_integration enabled no-cursor
cursor_shape block
cursor_blink_interval 0

window_margin_width 5

# Tweaks
enable_audio_bell no

background_opacity 0.80

# Terminal

term xterm
